name : CI/CD AWS S3

on :
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 코드 체크아웃
        uses: actions/checkout@v3

      - name: AWS IAM 사용자 설정
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: AKIAVUV3427FAJA2PBGB
          aws-secret-access-key: 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
          aws-region: ap-northeast-2
      - name: 리액트 빌드
        run: |
          npm install build
          npm run build
      - name: S3 에 업로드
        run: aws s3 sync build/ s3://itbambucket --acl public-read
        env:
          AWS_ACCESS_KEY_ID: AKIAVUV3427FAJA2PBGB
          AWS_SECRET_ACCESS_KEY: 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
